"""
Django settings for emart project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-gg0a1sbd*mi8$c0q5odh195u!x-q31u9+8#5uw$s_wq9fc43%^"

# stripe keys
STRIPE_SECRET_KEY = 'sk_test_51MyUkgSDGuZOyrByhHpjZSWT5QrJUOSJy3GXSqq0hDX6qorowONxRAX4gCxkKS8QeXgKlMPwO7qCo6b0d3kwkdem00Gy03THZS'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51MyUkgSDGuZOyrByAejwPkghVVL9yBOBquMZO5ivjMYGNytlo2LVWUPOSWMPF2iAq4Y9LTwrj0Yi0pjz4IIU00xL00vmHZq9RY'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',   
    "core",
    'account_app',
    "payments",
   
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "emart.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR /"templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.common_data"
            ],
        },
    },
]

WSGI_APPLICATION = "emart.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS=[BASE_DIR / "static"]
STATIC_ROOT ="static_root"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#Authentication related URLs
LOGIN_URL = "account_app:login"
LOGOUT_URL = "account_app:logout"
LOGIN_REDIRECT_URL = "core:home"
LOGOUT_REDIRECT_URL = "account_app:login"

# email Integration
EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / "tmp/mails/"

EMAIL_HOST = 'smtp.google.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'kavishnudath@gmail.com'
EMAIL_HOST_PASSWORD ='kurussarur123'

EMAIL_USE_TLS = True


#reCaptcha credentials  
GOOGLE_RECAPTCHA_SITE_KEY = "6LclRj4kAAAAACSxqPnhvY80E7elH9Hf6AzQMlsQ"
GOOGLE_RECAPTCHA_SECRET_KEY = "6LclRj4kAAAAAIMuxKUsx-o2pnBaO7Ey-kCOwuXV"
GOOGLE_RECAPTCHA_VERIFY_URL ="https://www.google.com/recaptcha/api/siteverify"
GOOGLE_API_KEY = "AIzaSyC0lidOwtqgIeBweyZtoXTuPMkN9HStuf0"

#socialmedia integration
SITE_ID = 1

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {
            'access_type': 'online'
        },
        'APP': {
            'client_id':"912459305573-6r8ii0tu1m2jnukncfc8fog7lbk51jcl.apps.googleusercontent.com",
            'secret': "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",
            'key': ''
        }
    }
}
