# Generated by Django 4.1.7 on 2023-03-15 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_name", models.CharField(max_length=120)),
                ("landmark", models.CharField(max_length=64)),
                ("place", models.CharField(max_length=64)),
                ("district", models.CharField(max_length=64)),
                ("state", models.CharField(max_length=64)),
                ("contry", models.CharField(max_length=64)),
                ("post_office", models.CharField(max_length=64)),
                ("post_code", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="LocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lattitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=16)),
                ("last_name", models.CharField(max_length=16)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("T", "Transgender")],
                        max_length=3,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/user.jpg",
                        upload_to="accounts_app/profile/image/",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "addresses",
                    models.ManyToManyField(blank=True, to="account_app.addressmodel"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="addressmodel",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account_app.locationmodel",
            ),
        ),
    ]
